# Haskell stack project Github Actions template
# https://gist.github.com/mstksg/11f753d891cee5980326a8ea8c865233
#
# To use, mainly change the list in 'plans' and modify 'include' for
# any OS package manager deps.
#
# Currently not working for cabal-install >= 3
#
# Based on https://raw.githubusercontent.com/commercialhaskell/stack/stable/doc/travis-complex.yml
#
# TODO:
# * cache (https://github.com/actions/cache)
#     but this is too small. native cacheing will come soon
#     https://github.community/t5/GitHub-Actions/Caching-files-between-GitHub-Action-executions/m-p/30974/highlight/true#M630
#     so we can wait for then.
# * support for cabal-install >= 3

name: Tests CI

on:
  push:
  schedule:
  - cron: "0 0 * * 1"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        # use this to specify what resolvers and ghc to use
        plan:
        - { build: stack, resolver: "--resolver lts-9"  }    # ghc-8.0.2
        - { build: stack, resolver: "--resolver lts-11"  }   # ghc-8.2.2
        - { build: stack, resolver: "--resolver lts-12"  }   # ghc-8.4.4
        # - { build: stack, resolver: "--resolver lts-13"  }  redundant because lts-14 checks ghc-8.6 already
        - { build: stack, resolver: "--resolver lts-14"  }   # ghc-8.6.5
        - { build: stack, resolver: "--resolver nightly" }
        - { build: stack, resolver: ""                   }
        # use this to include any dependencies from OS package managers
        include: []
        # - os: macOS-latest
        #   brew: anybrewdeps
        # - os: ubuntu-latest
        #   apt-get: happy libblas-dev liblapack-dev

    runs-on: ${{ matrix.os }}
    steps:
    - name: Install OS Packages
      uses: mstksg/get-package@v1
      with:
        apt-get: ${{ matrix.apt-get }}
        brew: ${{ matrix.brew }}
    - uses: actions/checkout@v2

    - name: Cache Stack
      id: cache-stack
      uses: actions/cache@v1
      with:
        path: ~/.stack
        key: ${{ runner.os }}-stack-v1

    - name: Cache Cabal
      id: cache-cabal
      uses: actions/cache@v1
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-cabal-v1

    - name: Build
      run: |
        stack build --ghc-options="-Werror" --only-dependencies

    - name: Test
      run: |
        stack test --ghc-options="-Werror"